version: "3"

services:
  jeeves-pizza-api:
    build: .
    image: "jeeves-pizza-api"
    container_name: "jeeves-pizza-api"
    working_dir: "/api"
    command: "npm run production"
    restart: always
    ports:
      - "80:8080"
    volumes:
      - "./persist:/api/persist"
    environment:
      PRODUCTION: 1
      PORT: 8080
      NODE_ENV: 'production'